Add example of testing layered effects with Clock
zio/zio pull request #4219
Opened 2020-09-19 09:26 UTC by leszekgruchala

This is a more complex test example using layers and TestClock. I had to spend some time to have it working, hopefully this will help other people too 👍 

Unfortunately, I cannot make it compilable under mdoc even though it compiles in [scastie](https://scastie.scala-lang.org/d1gkSoQzSSSwev3j2aISMA). 

```
error: /Users/lgr/projects/opensource/zio/docs/howto/test_effects.md:342:63: type mismatch;
 found   : repl.MdocSession.App1.ZIO[Any,Exception,Unit]
 required: zio.ZIO[?,?,Any]
        (ZIO.sleep(10.seconds) *> promise.succeed(1).tap(b => logger.log(b.toString)))
                                                              ^^^^^^^^^^^^^^^^^^^^^^
error: /Users/lgr/projects/opensource/zio/docs/howto/test_effects.md:349:64: type mismatch;
 found   : zio.IO[Exception,Nothing]
    (which expands to)  zio.ZIO[Any,Exception,Nothing]
 required: repl.MdocSession.App1.ZIO[Any,Exception,Unit]
    override def log(msg: String): ZIO[Any, Exception, Unit] = ZIO.fail(new Exception("BOOM"))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: /Users/lgr/projects/opensource/zio/docs/howto/test_effects.md:357:57: type mismatch;
 found   : repl.MdocSession.App1.ZIO[Any,Exception,Boolean]
 required: zio.ZIO[?,?,?]
      result  <- ZIO.service[SchedulingService].flatMap(_.schedule(promise)).run.fork
                                                        ^^^^^^^^^^^^^^^^^^^
error: /Users/lgr/projects/opensource/zio/docs/howto/test_effects.md:362:45: This operation assumes that your effect requires an environment. However, your effect has Any for the environment type, which means it has no requirement, so there is no need to provide the environment.
  testCase.provideSomeLayer[TestEnvironment](partialLayer)
                                            ^
```

Any idea how to solve it?

2020-09-22 19:01 UTC, leszekgruchala commented
I decided to remove `mdoc` from my example, I am unable to make it work. It works well in scastie.

2020-09-22 19:02 UTC, adamgfraser commented
Will take a look. Thanks for working on this!

2020-09-24 00:11 UTC, adamgfraser commented on docs/howto/test_effects.md
> +```
```suggestion
```scala mdoc:reset
```

2020-09-24 00:13 UTC, adamgfraser requested changes
@leszekgruchala You're getting the error because the definition of `ZIO` is being shadowed by the definition on line 199. You can use the `reset` command in `mdoc` to get a fresh scope. With this change your code compiles correctly when I run `mdoc` so then we should be good to go.

2020-09-24 06:30 UTC, leszekgruchala commented
@adamgfraser awesome, thank you, fixed!

2020-09-24 15:52 UTC, adamgfraser approved these changes
Thank you for adding this! 🙏

2020-09-24 15:52 UTC, merged