ZIO-Test: Solve the `test` conflict with `zio.test`.
zio/zio pull request #4532
Opened 2021-01-03 17:28 UTC by dkarlinsky

Adding `test` method to `AbstractRunnableSpec` seems to do the trick.
#4520

2021-01-05 23:17 UTC, adamgfraser requested changes
Looks great! As proof that this solves the conflict and prevent regressions it would be good to replace usages of `zio.test.test` in our own internal test suites with `test`.

2021-01-05 23:17 UTC, adamgfraser commented on examples/shared/src/test/scala/zio/examples/test/ExampleSpec.scala
> +import test._
```suggestion
import zio.test._
```

2021-01-08 04:06 UTC, jdegoes commented
Awesome!!!

2021-01-08 19:24 UTC, adamgfraser approved these changes

2021-01-08 19:25 UTC, merged