assertCompletesM
zio/zio pull request #4740
Opened 2021-02-25 20:06 UTC by emarx

This PR adds a function `assertCompletesM` to complement the existing `assertCompletes`

2021-02-26 16:09 UTC, regiskuckaertz commented
@emarx you will need to run `sbt prepare` to fix all those lint issues.

2021-02-26 16:11 UTC, regiskuckaertz commented on test/shared/src/main/scala/zio/test/package.scala
> +    assertMImpl(UIO(true))(Assertion.isTrue)
```suggestion
    assertMImpl(UIO.succeed(true))(Assertion.isTrue)
```
sorry to be pedantic, `UIO(x)` is when `x` is an effect.

2021-02-27 23:05 UTC, emarx commented
Thanks, @regiskuckaertz! Ran `sbt publish` and made the requested change.

2021-02-28 14:43 UTC, adamgfraser commented on test/shared/src/main/scala/zio/test/package.scala
> +    assertMImpl(UIO.succeed(true))(Assertion.isTrue)
Can actually be `succeedNow` for internal implementations like this.

2021-02-28 14:44 UTC, adamgfraser commented on test/shared/src/main/scala/zio/test/package.scala
> +
Unrelated changes?

2021-02-28 14:44 UTC, adamgfraser requested changes
Looks great! Just a couple of very minor comments.

2021-02-28 16:40 UTC, emarx commented on test/shared/src/main/scala/zio/test/package.scala
> +
Whoops, hadn't switched the scalafmt

2021-02-28 16:41 UTC, emarx commented
Thanks for your review, @adamgfraser! Comments addressed.

2021-02-28 17:05 UTC, adamgfraser approved these changes

2021-02-28 17:05 UTC, adamgfraser commented
Looks great! Will merge after all the checks pass.

2021-03-01 04:09 UTC, merged