Implement noneOrFail #4841
zio/zio pull request #4851
Opened 2021-03-29 16:45 UTC by tyrcho

2021-03-29 16:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=4851) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=4851) before we can accept your contribution.<br/><hr/>**Michel Daviot** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=4851) it.</sub>

2021-03-30 20:33 UTC, tyrcho commented
makes sense, I'll try that tomorrow

On Tue, Mar 30, 2021 at 2:57 PM Adam Fraser ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In core/shared/src/main/scala/zio/ZIO.scala
> <https://github.com/zio/zio/pull/4851#discussion_r604068136>:
>
> > @@ -3649,6 +3649,14 @@ object ZIO extends ZIOCompanionPlatformSpecific {
>     */
>    val none: UIO[Option[Nothing]] = succeedNow(None)
>
> +  /**
> +   * Lifts an Option into a IO.
> +   * If the option is empty it succeeds with Unit.
> +   * If the option is defined it fails with an error adapted with f.
> +   */
> +  def noneOrFail[E, O](o: Option[O], f: O => E): IO[E, Unit] =
>
> I would think noneOrFail would fail with O and noneOrFailWith would allow
> specifying a function to transform the error type.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zio/zio/pull/4851#pullrequestreview-624218699>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFK6ZDIHMKTCMMZ7MIE2DTTGHCUVANCNFSM4Z76GMQA>
> .
>

2021-03-31 15:51 UTC, tyrcho commented on core/shared/src/main/scala/zio/ZIO.scala
> +  def noneOrFail[E, O](o: Option[O], f: O => E): IO[E, Unit] =
I updated the code. Now the 2 methods are available.

2021-04-02 06:53 UTC, tyrcho commented
hey @adamgfraser , anything still needed before the merge ?

2021-04-06 01:20 UTC, adamgfraser requested changes
Looks great! A couple of minor comments. Could you also pull in the latest upstream changes? We've had some changes to our CI infrastructure recently so want to make sure everything is running. Thanks again for your work on this!

2021-04-06 01:20 UTC, adamgfraser commented on core/shared/src/main/scala/zio/ZIO.scala
> +  def noneOrFailWith[E, O](o: Option[O], f: O => E): IO[E, Unit] =
I would curry the arguments here for improved type inference.

2021-04-06 01:20 UTC, adamgfraser commented on core/shared/src/main/scala/zio/IO.scala
> +  def noneOrFailWith[E, O](o: Option[O], f: O => E): IO[E, Unit] =
You could have variants for some of the other type aliases that specialized the `E` type to `Throwable`.

2021-04-06 17:20 UTC, tyrcho commented
Thanks for the review !

I'll have a look at the changes you requested, I think they all make sense. I don't know when I can handle these, this week is going to be quite busy.

2021-04-07 10:42 UTC, tyrcho commented
I rebased from master branch, currified, and added an alias in RIO and Task. The Task alias really makes sense !

Anything else @adamgfraser ?

2021-04-07 14:17 UTC, adamgfraser approved these changes
Looks great!

2021-04-07 14:17 UTC, merged