Fix dead test
zio/zio pull request #5149
Opened 2021-05-26 12:21 UTC by kazchimo

2021-05-26 12:55 UTC, adamgfraser requested changes

2021-05-26 12:55 UTC, adamgfraser commented on core-tests/shared/src/test/scala/zio/ChunkSpec.scala
>      testM("specialized accessors") {
Good catch! Let's just make this a suite and each of the checks its own test within the suite.

2021-05-29 15:08 UTC, kazchimo commented on core-tests/shared/src/test/scala/zio/ChunkSpec.scala
> +          val expected = as ++ bs
😎

2021-05-29 15:22 UTC, adamgfraser approved these changes
Thank you!

2021-05-29 15:49 UTC, merged