Introduce Schedule.during operator
zio/zio pull request #5274
Opened 2021-07-02 10:45 UTC by agarella

This introduces an operator that allows a Schedule to recur for a given duration. As suggested here https://github.com/zio/zio/issues/4351

2021-07-03 04:12 UTC, jdegoes requested changes
Looks great!

How about we call it `upTo`, e.g. `Schedule.spaced(1.second).upTo(5.seconds)`.

2021-07-03 08:59 UTC, agarella commented
@jdegoes I've updated it according to your suggestion

2021-07-04 18:54 UTC, adamgfraser commented
@agarella Can you run `prepare` to format?

2021-07-04 19:48 UTC, adamgfraser approved these changes

2021-07-04 21:08 UTC, adamgfraser approved these changes

2021-07-04 21:14 UTC, merged