Implement iso/utf decoders
zio/zio pull request #5437
Opened 2021-08-21 09:51 UTC by paulpdaniels

Relates to #4886 

Ports the following operators from ZTransducer:
- ZSink.utfDecode
- ZSink.utf16Decode/ZSink.utf16LEDecode/ZSink.utf16BEDecode
- ZSink.utf32Decode/ZSink.utf32LEDecode/ZSink.utf32BEDecode
- ZSink.iso_8859_1Decode

Adds the following operator:
- ZStream#mkString a specialization of `intersperse`

2021-09-16 10:27 UTC, vigoo commented on streams-tests/shared/src/test/scala/zio/stream/experimental/ZSinkSpec.scala
> +            checkM(Gen.const("").map(s => Chunk.fromArray(s.getBytes(StandardCharsets.UTF_16BE))).map(Chunk.single)) {
This should be `Gen.anyString`

2021-09-16 10:31 UTC, vigoo commented on streams-tests/shared/src/test/scala/zio/stream/experimental/ZSinkSpec.scala
> +                  .fromChunks(byteChunks.toList: _*)
Instead of wrapping the `Chunk` in another `Chunk` and using `fromChunks` you could just use `ZIO.fromChunk` on the chunk you get from the array.

2021-09-16 15:51 UTC, vigoo commented on streams/shared/src/main/scala/zio/stream/experimental/ZSink.scala
> +      bytes.toList match {
We could skip the conversion to list and back to chunk and work directly on chunks (I know the 1.0 implementation  is like this too, so consider it as an optional optimization - we can also do it later)

2021-09-16 15:55 UTC, vigoo commented
Ready to merge if the test is fixed

2021-09-16 16:03 UTC, vigoo requested changes
Ready to merge if the test is fixed

2021-09-23 18:33 UTC, merged

2021-09-24 03:09 UTC, paulpdaniels commented
Woah thanks @vigoo! I did not register the notifications.