Run Test/doc on only one version of Scala to cut down on time (curren…
zio/zio pull request #5607
Opened 2021-09-14 13:48 UTC by sideeffffect

…tly 50 mins)

2021-09-14 13:49 UTC, adamgfraser approved these changes

2021-09-14 13:50 UTC, adamgfraser commented
@sideeffffect Thank you! 🙏

2021-09-16 01:57 UTC, jdegoes approved these changes

2021-09-16 07:05 UTC, adamgfraser requested changes
@sideeffffect Since we merged the other PR to address this do you want to keep this open to make further improvements or close it?

2021-09-16 19:11 UTC, sideeffffect commented
I think, we can close this :wink: We can always resuscitate later.

2021-09-16 19:11 UTC, closed without merging