add padToMod in Chunk of bits
zio/zio pull request #5941
Opened 2021-10-31 10:46 UTC by helanto

Deals with requirement 7 of #5050

2021-11-05 02:44 UTC, adamgfraser commented on core-tests/shared/src/test/scala/zio/BitChunkSpec.scala
> +  val genBitChunk: Gen[Random with Sized, Chunk[Boolean]] = for {
Need to use `asBits` here to construct a `BitChunk`.

2021-11-05 02:45 UTC, adamgfraser commented on core/shared/src/main/scala/zio/Chunk.scala
> +  def padToMod(n: Int)(implicit ev: A <:< Boolean): Chunk[Boolean] =
This needs to have a lower level implementation on the `BitChunk` data types to have the performance we are looking for.

2021-11-05 02:46 UTC, adamgfraser requested changes
See comments below about using the `BitChunk` data type, which provides a more optimized representation of a chunk of bits than just a `Chunk[Boolean]`.

2022-11-23 10:55 UTC, jdegoes commented
@helanto Will close for now. Please re-open if you get a chance to push this through!

2022-11-23 10:55 UTC, closed without merging