Implement shift left and right in Chunk[Boolean]
zio/zio pull request #5945
Opened 2021-10-31 13:02 UTC by koukoustath

number 6 of issue: #5050

2021-11-05 02:28 UTC, adamgfraser commented on core-tests/shared/src/test/scala/zio/BitChunkSpec.scala
> +  val genBitChunk: Gen[Random with Sized, Chunk[Boolean]] = for {
To construct a `BitChunk` you need to call `asBits` on a `Chunk[Byte]`.

2021-11-05 02:30 UTC, adamgfraser commented on core/shared/src/main/scala/zio/Chunk.scala
> +  def <<(n: Int)(implicit ev: A <:< Boolean): Chunk[Boolean] =
We want to provide optimized versions of these operators on `BitChunk`.

2021-11-05 02:31 UTC, adamgfraser commented on core/shared/src/main/scala/zio/Chunk.scala
> +  def >>(n: Int)(implicit ev: A <:< Boolean): Chunk[Boolean] =
Would be nice to provide a version of `>>>` as well.

2021-11-05 02:32 UTC, adamgfraser requested changes
Looks like you are off to a good start here but there is more work you are going to need to use the `BitChunk` data type and provide an optimized implementation of these operators.

2022-11-16 16:07 UTC, koukoustath commented
@adamgfraser 
Has this functionality been implemented? 

I see that the related [issue](https://github.com/zio/zio/issues/5050) has been closed.

Just asking to close the PR if it is already implemented. Thanks

2022-11-23 11:00 UTC, jdegoes commented
@koukoustath This does not look completed. We need definitions of left/right shift in `Chunk[Boolean]`, which do not exist, and then we need overrides on them for the packed classes, which also do not exist.

Please re-open if you want to continue your work here, and thanks for the PR!

2022-11-23 11:00 UTC, closed without merging