Slightly Simplify ZIO#scheduleBackground Implementation
zio/zio pull request #6496
Opened 2022-03-29 23:03 UTC by adamgfraser

2022-03-30 08:44 UTC, jdegoes requested changes
This looks good to me. However, it also occurs to me that `scheduleFork` may be a better name here than `scheduleBackground` (just based on other names we are using). Would you mind making this change at the same time?

2022-03-30 09:56 UTC, vigoo commented
or `scheduleForked`?

2022-03-30 11:32 UTC, adamgfraser commented
Sure. Renamed to `scheduleFork`. I think that is slightly idiomatic as we also have `reloadFork`, `drainFork`, and so on but no `forked` variants.

2022-03-31 06:05 UTC, vigoo approved these changes

2022-03-31 11:14 UTC, jdegoes approved these changes

2022-03-31 11:14 UTC, merged