Documentation of Migrating from `ZManaged` to `Scope`
zio/zio pull request #6524
Opened 2022-04-02 13:25 UTC by khajavi

2022-04-02 15:21 UTC, adamgfraser commented
There is some question here of how much we want to push people to the `managed` package versus just moving to scopes. I tend to think given how successful people have been in moving to scopes that we should push in that direction first. So an overall message like "Migrating to scopes is easy and you can do it like this ... if you have a lot of code that used `ZManaged` and you just don't want to deal with it right now you can do this ..."

2022-04-03 13:42 UTC, jdegoes approved these changes

2022-04-04 11:09 UTC, khajavi commented
@adamgfraser 
Incorporated your feedback and added some more notes about the ZManaged solution and its drawbacks.

2022-04-04 12:42 UTC, adamgfraser requested changes
This looks really good. I think maybe we could provide a little more of a step by step path for migrating from `ZManaged` to `Scope`. Something like:

1. Replace all references to `ZManaged[R, E, A]` with `ZIO[R with Scope, E, A]`
2. Replace all references to `resource.use(f)` with `ZIO.scoped(resource.flatMap(f))`
3. Replace all `ZManaged` constructors with `ZIO.acquireRelease` or one of its variants
4. Replace all usages of `Layer(resource)` or `resource.toLayer` with `ZLayer.scoped(resource)`, all references  to `ZStream.managed(resource)` with `ZStream.scoped(resource)`, and so on for similar constructors
5. Delete all uses of `toManaged_`
6. Replace all uses of `toManaged(finalizer)` with `withFinalizer(finalizer)`

2022-04-04 23:27 UTC, khajavi commented
@adamgfraser 
Thanks for your reviews.
Incorporated!

2022-04-04 23:38 UTC, adamgfraser commented on docs/howto/migrate/migration-guide.md
> ++  def make[R, E, A](get: => ZIO[R, E, A], size: => Int): ZIO[R with Scope, Nothing, ZPool[E, A]]
May want to use a different example here.

2022-04-05 13:52 UTC, adamgfraser approved these changes
Thanks for your work on this! This is going to make it a lot easier for people to upgrade to using scopes!

2022-04-05 13:52 UTC, merged