Simplification of concurrent data types
zio/zio pull request #6650
Opened 2022-04-18 11:23 UTC by khajavi

Addresses #6632

2022-04-18 11:23 UTC, khajavi commented
@adamgfraser 
It's ready for your review.

2022-04-18 12:45 UTC, adamgfraser requested changes
One minor comment. Otherwise looks great!

2022-04-18 12:45 UTC, adamgfraser commented on docs/howto/migrate/migration-guide.md
>  | `RefM#dequeueRef`       | `Ref.Synchronized#SubscriptionRef`     |
`SubscriptionRef` is in ZIO Stream.

2022-04-19 06:00 UTC, khajavi commented on docs/howto/migrate/migration-guide.md
>  | `RefM#dequeueRef`       | `Ref.Synchronized#SubscriptionRef`     |
fixed that!

2022-04-19 12:40 UTC, adamgfraser approved these changes

2022-04-19 12:40 UTC, merged