Add readFileString and writeFileString convenience methods
zio/zio pull request #6655
Opened 2022-04-18 18:46 UTC by kitlangton

`readFileString` is perhaps not the safest method—but it is most convenient :)

2022-04-18 20:03 UTC, adamgfraser requested changes
Great to add these!

Our existing naming convention from `ZStream` has been:

- `fromPath` - takes a `Path`
- `fromFile` - takes a `File`
- `fromFileName` - takes a `String`

So I think maybe `readFileString` should be `readFileName` to indicate that it takes a file name versus an actual file and then maybe we should use `Default` to indicate that this just reads the whole thing into memory in the simplest way possible? So it would be `readFileDefault` and `readFileNameDefault`?

Or we could revisit the `ZStream` naming conventions. Just trying to think about how to keep everything consistent.

Also, I think all of these operators should take their parameters by name, which I think is going to force some renaming due to type erasure.

2022-04-19 11:28 UTC, vigoo commented
If we add these, maybe we could also have variants returning `Chunk[Byte]` (although I would probably just promote using the `ZStream` variants)

2022-04-19 12:36 UTC, adamgfraser commented
Yeah, I think we might want `ZStream` variants of these `default` operators as well. I think the idea here is to make it easier to do simple demonstrations of things like reading from a file or writing to a file without having to immediately getting into all the issues around encoding and so on.

2022-04-25 21:19 UTC, adamgfraser reviewed
Did you want to do the by name parameters here or in a follow up?

2022-04-25 21:25 UTC, adamgfraser approved these changes

2022-04-25 21:25 UTC, merged