WIP Fixed #5595 - Added GraalVM native test aspects
zio/zio pull request #6715
Opened 2022-04-25 19:45 UTC by tewecske

Adds a new flag in TestPlatform, which is `isGraalVM` and also TestAspects `graalVMOnly` and `exceptGraalVM`.

2022-04-25 19:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=6715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=6715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=6715) it.</sub>

2022-04-25 21:28 UTC, kitlangton commented
Hey @tewecske! That was fast! (Saw you asking about contributing on the discord) Welcome welcome!

2022-04-25 21:29 UTC, kitlangton approved these changes, later dismissed

2022-04-25 21:36 UTC, adamgfraser commented on test/jvm/src/main/scala/zio/test/TestPlatform.scala
> +   * java.vendor.url -> https://www.graalvm.org/
I think we can remove.

2022-04-25 21:38 UTC, adamgfraser requested changes
Looks like you just need to format (you can do `fmt`) and merge upstream changes.

2022-11-23 11:33 UTC, jdegoes commented
@tewecske This code no longer compiles. Please re-open if you get a chance to update it!

2022-11-23 11:33 UTC, closed without merging