Fix OR semantics for SmartAssertions
zio/zio pull request #6887
Opened 2022-05-31 18:10 UTC by minedeljkovic

Attempt to fix #6886 based on [the comment](https://github.com/zio/zio/issues/6886#issuecomment-1142329765) from @adamgfraser.

2022-05-31 18:11 UTC, minedeljkovic commented on test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala
> +    },
I'm not sure we want this semantics for rhs, though.
For example, such boolean expression will fail in plain Scala `option.get == 1 || option.isEmpty`.

2022-11-23 11:25 UTC, jdegoes commented on test/shared/src/main/scala/zio/test/Trace.scala
> +        case (_, Result.Succeed(true)) => Result.succeed(true)
I don't think we want this because it violates the ordinary meaning of `false || true`.

2022-11-23 11:26 UTC, jdegoes requested changes
Just one revision, then will be good to merge. Thanks!

2022-11-23 11:26 UTC, jdegoes commented
@minedeljkovic Please re-open if you get a chance to make the one suggested revision. Thanks!

2022-11-23 11:26 UTC, closed without merging