Documentation: Structured Concurrency and Background Processes
zio/zio pull request #7188
Opened 2022-08-10 10:04 UTC by khajavi

2022-08-10 10:53 UTC, khajavi commented
@adamgfraser 
I incorporated your comments in #7174 in this PR and closed that.

2022-08-10 14:44 UTC, adamgfraser requested changes
I think it may still be clearer to describe it as (1) fork with automatic supervision / fork as daemon / fork in Scope versus fork in global scope / fork in local scope / fork in specific scope for the reasons discussed previously. Otherwise looks good.

2022-08-11 10:03 UTC, khajavi commented
@adamgfraser 
Oops! I forgot to remove extra sections from the latest work. 
Anyway, I also categorized them into four sections and described each according to your comment. And I added a note on the `Scope` data type to clear about why we use that. 
Now I think it is ready to go

2022-08-11 16:38 UTC, jdegoes approved these changes

2022-08-11 17:05 UTC, adamgfraser approved these changes

2022-08-11 17:05 UTC, merged