make existsIterable assertion more strict
zio/zio pull request #7317
Opened 2022-09-06 21:34 UTC by myazinn

Let's say we've got the following test

```scala
import zio.test._

object MySpec extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("sweet") {
      test("test") {
        val exists = Seq(1, 2, 3).exists(i => if (i == 1) ??? else i == 2)
        assertTrue(exists)
      }
    }
}
```
If we run it, it fails as expected
```
+ sweet
  - test
    Exception in thread "zio-fiber-25" scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
        at zio.MySpec.spec(MySpec.scala:8)
0 tests passed. 1 tests failed. 0 tests ignored.
```
However, if we just inline `exists` variable, the test unexpectedly passes 
```scala
import zio.test._

object MySpec extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("sweet") {
      test("test") {
        assertTrue(Seq(1, 2, 3).exists(i => if (i == 1) ??? else i == 2))
      }
    }
}
```
```
+ sweet
  + test
1 tests passed. 0 tests failed. 0 tests ignored.
```
I actually faced this corner case and was surprised that my tests pass when they shouldn't.
Proposed solution to this issue is somewhat arbitrary, I don't know if it's better to fail the test with `Result.die(???)` using the first found exception or to use `Result.succeed(false)` and combine errors, but the latter looks one more informative to me.
So if you apply suggested changes and run the test again, you'll see something like this
```
+ sweet
  - test
    ? 1 element satisfied the predicate but it's discarded since the predicate threw an exception on 1 element
    Seq(1, 2, 3).exists(i => if (i == 1) ??? else i == 2)
          ? ERROR: scala.NotImplementedError: an implementation is missing
            scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
            zio.MySpec$.$anonfun$spec$5(MySpec.scala:9)
            scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
          Seq(1, 2, 3).exists(i => if (i == 1) ??? else i == 2)
          at foo/bar/buzz/zio/MySpec.scala:9
    (1, 2, 3) = List(1, 2, 3)
    Seq = scala.collection.immutable.Seq$@1855a2b8
    at foo/bar/buzz/zio/MySpec.scala:9

0 tests passed. 1 tests failed. 0 tests ignored.

```
Note that this solution still a little bit inconsistent with Scala's `exists`, because it will fail event if the exception was thrown after the predicate was satisfied at least once. It could be fixed, but maybe it's a feature?
Also, I believe this PR might break some test somewhere. Don't think it's a big issue, but still needs to be highlighted.

2022-10-17 14:11 UTC, narma commented
Any chance it can be included in upcoming release?

2022-10-23 16:07 UTC, myazinn commented
@kitlangton could you please take a look if you get a chance?

2022-11-23 12:29 UTC, jdegoes requested changes
Looks good to me, can you add tests to verify the original issue is fixed?

2022-11-23 17:35 UTC, myazinn commented
@jdegoes thanks for the review
I've added tests

2022-11-23 17:37 UTC, adamgfraser commented
I think it would be good to make this mirror the behavior of `exists` on Scala collections where subsequent elements would not be evaluated if an element satisfied the predicate.

2022-11-25 09:24 UTC, jdegoes approved these changes

2022-11-25 09:24 UTC, merged