Add methods to get at least a certain number of Semaphore permits.
zio/zio pull request #7337
Opened 2022-09-12 01:13 UTC by shawjef3

This allows clients to not block forever if they might never get the full number of permits they'd ideally like.

2022-09-12 01:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/zio/zio?pullRequest=7337) <br/>All committers have signed the CLA.

2022-09-12 01:53 UTC, adamgfraser reviewed
This could potentially be simplified to `acquireUpTo` for consistency with `Queue#takeUpTo` with the contract that it tries to acquire up to the specified number of permits and semantically blocks until at least one permit is available.

2022-09-12 02:01 UTC, adamgfraser commented
Or `acquireBetween` for the more general version.

2022-09-15 01:04 UTC, shawjef3 commented
@adamgfraser I renamed the `Range` methods to be `Between` instead.

2022-09-15 01:25 UTC, shawjef3 commented
@adamgfraser I also added methods for taking at least N or at most N permits.

2022-09-15 04:06 UTC, adamgfraser requested changes
Let's stick with the `XYZBetween` and `XYZUpTo` variants.

2022-09-15 13:32 UTC, shawjef3 commented
@adamgfraser done.

2022-09-15 13:40 UTC, shawjef3 commented
I had to force push my branch to fix the author of some commits. Some minecraft thing I built edited my global git config. Very annoying.

2022-09-17 13:48 UTC, shawjef3 commented
@adamgfraser it looks like the build failed due to the new methods marking it as binary incompatible.

2022-09-17 16:02 UTC, shawjef3 commented
@adamgfraser The binary compatibility check failed because if any clients already extended `Semaphore`, their builds will fail because they didn't implement the new methods. Scalac won't let someone do that because `Semaphore` is `sealed`, but Java code could. Is it okay with you if we add exceptions for these methods so mima ignores them?

2022-09-17 16:07 UTC, adamgfraser commented
@shawjef3 I think we might remove the seal at some point so we don't we just expose these methods on `TSemaphore`. That way we keep the `Semaphore` interface nice and simple and if people need to do fancier stuff they can use the `TSemaphore`.

2022-09-18 14:20 UTC, shawjef3 commented
@adamgfraser I see. Do you think we should remove the new methods from `Semaphore` then? I can remove them and then the mima check should succeed.

2022-09-18 14:21 UTC, adamgfraser commented
@shawjef3 Yes.

2022-09-18 14:32 UTC, shawjef3 commented
Or we can add the exceptions since no one should be extending `Semaphore` anyway.

2022-09-20 14:29 UTC, adamgfraser approved these changes

2022-09-20 14:29 UTC, merged

2022-09-20 14:49 UTC, adamgfraser commented
@shawjef3 Thank you for your work on this! 🙏