Update Scala Version
zio/zio pull request #7377
Opened 2022-09-29 18:21 UTC by adamgfraser

Resolves #7376.

2022-09-29 18:56 UTC, vigoo approved these changes, later dismissed

2022-09-29 21:35 UTC, Wosin submitted a review, later dismissed

2022-09-30 06:40 UTC, narma commented
Looks like we should wait for 2.3.10 https://twitter.com/scala_lang/status/1575548918858887168

2022-10-09 20:07 UTC, sideeffffect commented
The 2.13.10 release is [rolling out now](https://contributors.scala-lang.org/t/scala-2-13-10-release-planning/5943/9). AFAIK we just need to wait for Silencer ( https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.10 ) and then we can upgrade too :crossed_fingers:

2022-10-21 20:22 UTC, sideeffffect commented
@adamgfraser new Silencer for 2.13.10 has been released. We can now upgrade to 2.13.10, Silencer [1.7.12](https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.10/).

Maybe we won't need all the changes to the code with 2.13.10 (unlike with 2.13.9).

2022-10-21 22:09 UTC, sideeffffect requested changes
https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-testkit_2.13.10/

2022-10-21 22:09 UTC, sideeffffect commented on project/plugins.sbt
> +addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"                  % "0.10.3")
needs to be updated to 0.10.4

2022-10-21 22:09 UTC, sideeffffect commented on build.sbt
> +    libraryDependencies += "ch.epfl.scala" %% "scalafix-core" % "0.10.3"
needs to be updated to 0.10.4

2022-10-22 13:13 UTC, sideeffffect commented on project/plugins.sbt
> +addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"                  % "4")
typo :smile_cat:
```suggestion
addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"                  % "0.10.4")
```

2022-10-23 16:41 UTC, sideeffffect commented
All tests green :tada:

2022-10-26 09:49 UTC, sideeffffect commented
@adamgfraser @mijicd ping :smile_cat:

2022-10-26 09:56 UTC, mijicd approved these changes

2022-10-26 09:57 UTC, merged