ifNone, ifNoneZIO for ZIO[R, E, Option[A]]
zio/zio pull request #8308
Opened 2023-08-08 19:36 UTC by mtumilowicz

2023-08-08 19:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=8308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=8308) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=8308) it.</sub>

2023-08-09 17:17 UTC, adamgfraser requested changes
@mtumilowicz Hi! Thanks for your PR!

I don't think it makes sense to add more highly specialized operators like this. These operators can easily be implemented in terms of `map` and `flatMap`. While specialized operators can have some value in providing a more fluent API they also have a cost in that they make the overall number of operators on ZIO larger and make it harder for users to find the operators they are looking for. I think we are already past the point at which adding specialized operators that are only minor variations of existing operators makes sense.

2023-08-09 21:08 UTC, mtumilowicz commented
@adamgfraser - kk, no problem, we just needed them in the company I'm working for so I thought that maybe it can be useful, but I totally agree with the approach to specialised operators

2023-08-09 21:08 UTC, closed without merging

2023-08-10 14:37 UTC, adamgfraser commented
@mtumilowicz Totally! It is definitely a balance. You might also want to check out the `some`, `unsome`, and `orElseOptional` operators for an alternative take on this.