Update chunk.md
zio/zio pull request #8380
Opened 2023-09-11 10:48 UTC by markusheilig

Being more explicit. Why? When using the word 'they', it sounded for me that ZIO Chunks were painful to use and don't integrate well into functional code.

I also asked ChatGPT:
Given the following code documentation, I have a question: Which one is painful to use and does not integrate well into functional code, is it ZIO Chunks or Arrays? "Arrays are fast and don’t box primitive values. ZIO Chunk is a wrapper on Java array. So also Chunks have zero boxing for primitives, but due to ClassTag requirements and mutability, they are painful to use and don’t integrate well into functional code."

ChatGPT's answer:
Based on the provided code documentation, it appears that ZIO Chunks are the ones that are considered painful to use and do not integrate well into functional code. Here's the relevant statement:

"Chunks have zero boxing for primitives, but due to ClassTag requirements and mutability, they are painful to use and don’t integrate well into functional code."

This statement suggests that while Chunks have certain performance benefits (zero boxing for primitives), they come with downsides such as ClassTag requirements and mutability, which make them less convenient and less suitable for functional programming compared to Arrays. Arrays, on the other hand, are described as fast and not boxing primitive values, which makes them more suitable for certain use cases.

2023-09-11 19:00 UTC, adamgfraser commented on docs/reference/stream/chunk.md
> +Arrays are fast and don’t box primitive values. ZIO Chunk is a wrapper on Java array. So also Chunks have zero boxing for primitives, but due to ClassTag requirements and mutability, arrays are painf
```suggestion
Arrays are fast and don’t box primitive values but due to `ClassTag` requirements and mutability they are painful to use and don't integrate well info functional code. ZIO chunks are backed by arrays so they also have zero boxing for primitives while providing an immutable interface and avoiding `ClassTag` requirements.
```

2023-09-11 19:03 UTC, adamgfraser requested changes
Yes I think this sentence is somewhat confusing now. It is a little awkward even with this change. See suggestion below.

2023-09-11 19:04 UTC, markusheilig commented on docs/reference/stream/chunk.md
> +Arrays are fast and don’t box primitive values. ZIO Chunk is a wrapper on Java array. So also Chunks have zero boxing for primitives, but due to ClassTag requirements and mutability, arrays are painf
Love that!

2023-09-15 11:25 UTC, jdegoes approved these changes, later dismissed

2023-09-15 20:20 UTC, merged