Fixed #8298: added ZStream.readFile support for ScalaNative
zio/zio pull request #8609
Opened 2024-01-08 18:55 UTC by melsonic

Fixes #8298 
/claim #8298

2024-01-08 18:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=8609) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=8609) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=8609) it.</sub>

2024-01-08 18:57 UTC, adamgfraser requested changes
Can you please add tests for this?

2024-01-08 18:59 UTC, melsonic commented
> Can you please add tests for this?

sure

2024-01-08 22:35 UTC, jdegoes commented on streams/shared/src/main/scala/zio/stream/ZStream.scala
> +      ZIO.attemptBlockingIO(s.mkString)
Creating one string from `Source#mkString` is going to be very inefficient.

2024-01-09 18:40 UTC, adamgfraser commented
@melsonic This was already implemented in #8364. Sorry for the confusion!

2024-01-09 18:40 UTC, closed without merging