fix :Added ZIO.readFile support for ScalaJS
zio/zio pull request #8619
Opened 2024-01-14 07:37 UTC by guptadeepak8

fixes #8295
/claim #8295

2024-01-14 07:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=8619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=8619) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=8619) it.</sub>

2024-01-14 13:26 UTC, adamgfraser commented on core-tests/js/src/test/scala/zio/interop/ZIOPlatformSpecificTest.scala
> +object ZIOPlatformSpecificTest extends DefaultRunnableSpec {
```suggestion
object ZIOPlatformSpecificSpec extends DefaultRunnableSpec {
```

2024-01-14 13:27 UTC, adamgfraser commented on core/js/src/main/scala/zio/ZIOPlatformSpecific.scala
> +import org.scalajs.dom.Blob
```suggestion
```

2024-01-14 13:27 UTC, adamgfraser commented on core/js/src/main/scala/zio/ZIOPlatformSpecific.scala
> +import zio._
```suggestion

```

2024-01-14 13:28 UTC, adamgfraser commented on core/js/src/main/scala/zio/ZIOPlatformSpecific.scala
> +  def readFile(file: js.File)(implicit trace: Trace): Task[String] =
This should be a method on the companion object, not the trait. It is constructing a new workflow, not transforming an existing one.

2024-01-14 13:29 UTC, adamgfraser requested changes
Thanks for working on this! Left some comments.

2024-01-14 22:38 UTC, guptadeepak8 commented
@adamgfraser  i have made the changes

2024-01-15 05:03 UTC, adamgfraser commented on core/js/src/main/scala/zio/ZIOPlatformSpecific.scala
> +
```suggestion
```

2024-01-15 05:03 UTC, adamgfraser requested changes
Can you format?

2024-01-16 21:22 UTC, guptadeepak8 commented
@adamgfraser made changes

2024-01-17 00:31 UTC, adamgfraser commented
These changes to not address my previous review comments and the code does not appear to have ever been compiling or even to use valid operators. Closing.

2024-01-17 00:31 UTC, closed without merging