Fix issue with zio.test.Gen.fromIterable generating deterministic output
zio/zio pull request #9326
Opened 2024-11-21 23:23 UTC by nocodeventure-nl

Adjust Gen composition to ensure that combining Gen.fromIterable with other generators in different orders results in non-deterministic output. This resolves issue #9101.

/claim #9101

The key changes:

- Modified fromIterable to include a random element by using ZStream.fromZIO(Random.nextInt) before generating the values
- This ensures that when combined with other random generators like Gen.uuid, the randomization behavior remains consistent regardless of order

2024-11-21 23:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio?pullRequest=9326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio?pullRequest=9326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio?pullRequest=9326) it.</sub>

2024-11-22 22:49 UTC, nocodeventure-nl commented
@jdegoes Could you please review this pull request when you have a moment? Thank you for your contributions!

2024-11-23 07:36 UTC, nocodeventure-nl commented
@felix-hedenstrom Do you have a moment to look at this? Thank you!

2024-12-03 22:02 UTC, soujiro32167 commented
Could this also be applied to `Gen.concatAll`? It would help resolve https://github.com/zio/zio/issues/9300

2024-12-04 08:25 UTC, melmathari commented
> Could this also be applied to `Gen.concatAll`? It would help resolve #9300

Change added

2024-12-04 09:13 UTC, melmathari commented
@felix-hedenstrom Can you please review this PR at your earliest convience? Thanks!

Also let me know if I should remove the last change, to accomodate for #9300

2024-12-04 10:54 UTC, melmathari commented
Test failing unrelated to our changes....

- TextCodecPipelineSpec - Text Decoders - utfDecode - UTF-16LE with BOM
        Exception in thread "zio-fiber-" java.nio.charset.MalformedInputException: Input length = 2
        	at zio.stream.ZPipeline$.$anonfun$decodeCharsWithDecoder$3(ZPipeline.scala:996)
        	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3237)
        	at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3246)
        	at zio.FiberRef$unsafe$$anon$2.$anonfun$getWith$1(FiberRef.scala:474)

2024-12-08 05:21 UTC, kyri-petrou requested changes
Thank you for the contribution! Unfortunately we really can't go with an implementation that relies on causing an OOM error to check whether a generator is finite. I'm going to leave this PR open for now in case you have any other ideas on how to check for infinite generators, but that is something that absolutely needs to be addressed

2024-12-08 05:21 UTC, kyri-petrou commented on test/shared/src/main/scala/zio/test/Gen.scala
> +          }
I'm sorry but we really can't do this. Besides making things extremely slow as we'll need to generate collections of several GBs in size, catching an OOM Error should never _ever_ be used as an expected condition

2024-12-08 07:43 UTC, closed without merging